CREATE TABLE `authToken` (
	token VARCHAR(255) NOT NULL,
	userId VARCHAR(255) NOT NULL,
	IP VARCHAR(255) NOT NULL,
	IPVia VARCHAR(255) NULL,
	IPForward VARCHAR(255) NULL,
	userAgent VARCHAR(255) NULL,
	userLanguage VARCHAR(255) NULL,
	HTTPAccept VARCHAR(255) NOT NULL,
	expires INT(10) NOT NULL,
	PRIMARY KEY (token)
) ENGINE=MyISAM